### ISSUE TITLE
CUDA integration

### ISSUE THREAD

**Issue by mtiezzi** [farrajota/criterion_filter#1]
Hi, 
I'm using your package for an university project. It's awesome, thanks for developing it.
Using standard CPU it works like a charm, however introducing CUDA make things very slow.
I think it behaves this way because inputs (that are in CUDA) are converted back to CPU each time to compare them.
Is it possible to integrate CUDA in your code (I'm using the SingleCriterionFilter) ?
Could you tell me where to operate and make changes? ( I am new to torch, I'm learning while doing this project).
Thank you

**Comment by farrajota** [comment]
I'll take a look at it and issue a fix in order to use CudaTensors.

**Comment by farrajota** [comment]
I've issued a [fix](https://github.com/farrajota/criterion_filter/commit/e85904c3c7db9631718f75bcf8e9e6ee1794bf57) and it should be now working properly with cuda tensors.

**Comment by mtiezzi** [comment]
Thanks,
but the fix seems to have broken the behaviour with MSECriterion.
In my code I have a neural network with four outputs, and I want to filter -1 target .
Before it worked with the following code:
`criterion=nn.MSECriterion() 
criterion = criterion_filter.Single (criterion, -1) 
criterion = nn.SequencerCriterion(criterion)`

This code that previously worked now gives the following error :
`/home/matteo/torch/install/bin/luajit: .../torch/install/share/lua/5.1/criterion_filter/Single.lua:57: attempt to index local 'v' (a number value)
stack traceback:
        .../torch/install/share/lua/5.1/criterion_filter/Single.lua:57: in function 'getFilteredIndexes'
        .../torch/install/share/lua/5.1/criterion_filter/Single.lua:103: in function 'forward'
        ...o/torch/install/share/lua/5.1/rnn/SequencerCriterion.lua:55: in function 'forward'
        checkpoint.lua:78: in function 'gradientUpgrade'
        checkpoint.lua:181: in main chunk
        [C]: in function 'dofile'
        ...tteo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670`

You can see this also executing the example number 2 in your readme
(even if in that case the error message  is different,
`/home/matteo/torch/install/bin/luajit: .../torch/install/share/lua/5.1/criterion_filter/Single.lua:57: attempt to call method 'repeatTensor' (a nil value)
stack traceback:
        .../torch/install/share/lua/5.1/criterion_filter/Single.lua:57: in function 'getFilteredIndexes'
        .../torch/install/share/lua/5.1/criterion_filter/Single.lua:103: in function 'forward'
        test2.lua:18: in main chunk
        [C]: in function 'dofile'
        ...tteo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670`
The different error depends on the fact that in this case the targets to filter are more than one, in my case only one).
Thanks and sorry to bother you.

**Comment by farrajota** [comment]
I've reverted the code back to a previous commit and it should be working like it previously was. My last fix tried to batch as much computations as possible using the torch API, but it meant to reduce the use cases to tensors with maximum dimension of 2. The current format is a trade-of between speed and usability, but it should be faster with `CudaTensors` than it was before. 

See if it works for you now and if the speed is bearable. If not I can deploy again the faster version I've used before in a different branch than the `master` but it will only work for 2D tensors.

**Comment by mtiezzi** [comment]
I have done some tests.
With the last code of criterion filter, using CPU to train for 50 epochs, with my dataset and net, takes 43.37 seconds.
Using CUDA it takes  222 seconds.
I wanted to use CUDA only to have an improvement in learning time (I need at least 10000 epochs for my training).
However I can continue to train using CPU, no problem.

What do you mean saying 2D tensors? The input to the criterion must have, in that case, size of 2? (and so the output of the net? I need the architecture to be like it is, so for me is impossible to modify the number of output).
If instead you meant it must be like {-1,-1,-1,-1}, for me is perfect

**Comment by farrajota** [comment]
I've completed some tests, and the performance impact I've noticed wasn't too dramatic. Maybe the complexity of your network does not justify the CPU to GPU data transfer delays and if you can train your network in a reasonable time then it's not that bad. 

I did find a bug for compound criterions `nn.CrossEntropyCriterion` where size mismatch issues happened and those were bound to buffer reuse and it is now working properly.

**Comment by mtiezzi** [comment]
Ok , thanks a lot.
I'll close the issue.
